services:
  mosdns:
    image: irinesistiana/mosdns
    container_name: mosdns
    hostname: mosdns
    restart: always
    mac_address: ${mosdnsmac}
    networks:
      macvlan:
        ipv4_address: ${mosdns4}
    volumes:
      - ./:/etc/mosdns
    command: start -c /etc/mosdns/config.yaml

networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}